--1. 전체 학과명, 계열 조회
SELECT DEPARTMENT_NAME "학과 명", CATEGORY 계열
FROM TB_DEPARTMENT;

--2. 학과별 정원 조회
SELECT DEPARTMENT_NAME ||'의 '||'정원은 '||CAPACITY||'명 입니다.' "학과별 정원"
FROM TB_DEPARTMENT;

--3
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN('A513079','A513090','A513091','A513110','A513119')
ORDER BY STUDENT_NAME DESC;

--4. 입학정원 20명이상 30명 이하인 학과 이름 계열 출력
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--5. 기술대학교에 총장을 제외하고는 모든 교수가 소속학과가 있음, 총장의 이름을 출력하시오
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--6. 학과가 지정되지 않은 학생 조회
SELECT *
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--7. 선수과목이 존재하는 과목들 과목번호 조회
SELECT CLASS_NO
FROM TB_CLASS
WHERE preattending_class_no IS NOT NULL;

--8. 대학교 계열들 총 조회
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

--9. 02학번 전주거주자들 모임 만들려고함, 휴학한 사람들을 제외한 학생들의 학번, 이름, 주민 출력
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N' AND SUBSTR(STUDENT_ADDRESS,1,2) = '전주' AND SUBSTR(ENTRANCE_DATE,1,2) = 02;