--1. 영문학(학과코드 002) 학생들 학번, 이름, 입학년도를 입학년도가 빠른순 (헤더는 학번, 이름, 입학년도 표시)
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

--2. 이름이 세글자가 아닌 교수의 이름과 주민번호 출력
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM tb_professor
WHERE LENGTH(PROFESSOR_NAME) != 3
ORDER BY PROFESSOR_NAME;

--3. 남자교수들 이름, 나이 출력, 나이 오름차순, 헤더 교수이름, 나이 / 나이는 만으로 표시
SELECT PROFESSOR_NAME 교수이름, EXTRACT(YEAR FROM SYSDATE) - (19||SUBSTR(PROFESSOR_SSN, 1,2)) 나이
FROM TB_PROFESSOR 
WHERE SUBSTR(PROFESSOR_SSN,8,1) IN('1','3')
ORDER BY 나이;

--4. 교수들 이름 중 성을 제외한 이름 출력, 헤더는 이름
SELECT SUBSTR(PROFESSOR_NAME, 2,2) 이름
FROM TB_PROFESSOR;

--5. 재수생 입학생을 구하시오, 19살에 입학하면 재수하지 않은 것임
SELECT *
FROM TB_STUDENT
WHERE 
    (EXTRACT(YEAR FROM ENTRANCE_DATE) -
    TO_NUMBER(TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN,1,6), 'RRMMDD'), 'YYYY'))) > 19;
    
--6. 2020년 크리스마스는 무슨 요일인가?
SELECT TO_CHAR(TO_DATE('20201225', 'YYYYMMDD'), 'DAY') 
FROM DUAL;

--7. TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD') 각각 몇년몇월몇일 / RR은 몇년 몇월 몇일
SELECT TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'DL'), TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'), 'DL')
FROM DUAL;

--8. 2000년대 이후 입학자는 학번이 A로 시작, 2000년도 이전 학번을 받은 학생들의 학번, 이름 조회
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

--9. 학번이 A517178인 한아름 학생 학점 총 평점, 단,점수반올림 소수점한자리까지 /헤더는 '평점'
SELECT ROUND(SUM(POINT),1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10 학과별 학생 수를 구하여 학과번호, 학생수 형태로 헤더를 만들어 결과값 출력
SELECT DEPARTMENT_NO 학과번호, COUNT(*) 학생수
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11. 지도교수 배정 못받은 학생의 수 조회
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12. 학번이 A112113인 김고운 학생의 년도 별 평점. 단, 헤더는 년도 / 년도별평점, 점수 반올림 소수점 한자리까지
SELECT SUBSTR(TERM_NO, 1, 4) 년도, ROUND(AVG(POINT), 1) "년도별 평점"
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
WHERE STUDENT_NO = 'A112113'
GROUP BY TERM_NO
ORDER BY 년도;

--13 학과별 휴학생 수
SELECT DEPARTMENT_NO, COUNT(CASE WHEN ABSENCE_YN = 'Y' THEN 1 END)
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--14 동명이인 학생 찾기
SELECT STUDENT_NAME, COUNT(*)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY STUDENT_NAME;

--15 학번이 A112113인 김고운학생의 년도, 학기별 평점과 년도별 누적평점, 총평점
SELECT SUBSTR(TERM_NO, 1, 4) AS 년도,
        SUBSTR(TERM_NO, 5,2) AS 학기,
       POINT AS "학기별 평점", 
       (SELECT SUM(POINT) 
       FROM TB_GRADE
       WHERE STUDENT_NO ='A112113'
       AND TERM_NO <= G.TERM_NO) AS "년도별 누적평점",
       (SELECT SUM(POINT) 
       FROM TB_GRADE
       WHERE STUDENT_NO = 'A112113'
       AND TERM_NO = G.TERM_NO) AS 총평점
FROM TB_GRADE G
WHERE STUDENT_NO = 'A112113'
ORDER BY 년도, TERM_NO